import { toISODate } from "./format";
import type {
  Activity,
  BidRecipient,
  Database,
  Organization,
  Project,
} from "./types";

// ---------------------------------------------------------------------------
// Seed pipeline for a Wasatch Front commercial roofer. Dates are generated
// relative to the day the store is first created, so a fresh clone always
// opens onto a live-looking board: things due today, a couple overdue, bids
// closing this week, installs spread across the next three quarters.
//
// Contact names are fictional. Company names are typical regional GCs and are
// placeholders for real relationship data.
// ---------------------------------------------------------------------------

const ORGS: Organization[] = [
  {
    id: "org-okland",
    name: "Okland Construction",
    type: "gc",
    city: "Salt Lake City",
    state: "UT",
    relationship: "preferred",
    paymentSpeed: "30–35 days",
    notes:
      "Best relationship in the book. Levels bids fairly and tells us where we sit. Prefers Carlisle assemblies.",
    contacts: [
      { name: "Ryan Delacroix", title: "Senior Estimator", email: "rdelacroix@example.com", phone: "801-555-0142" },
      { name: "Megan Alvarado", title: "Project Manager", email: "malvarado@example.com" },
    ],
  },
  {
    id: "org-bigd",
    name: "Big-D Construction",
    type: "gc",
    city: "Salt Lake City",
    state: "UT",
    relationship: "strong",
    paymentSpeed: "35–45 days",
    notes: "High volume. Wants scope letters clean and exclusions explicit.",
    contacts: [
      { name: "Cole Bannister", title: "Estimator", email: "cbannister@example.com", phone: "801-555-0119" },
    ],
  },
  {
    id: "org-layton",
    name: "Layton Construction",
    type: "gc",
    city: "Sandy",
    state: "UT",
    relationship: "strong",
    paymentSpeed: "45 days",
    notes: "Healthcare and institutional heavy. Long award cycles — be patient.",
    contacts: [
      { name: "Sasha Bergeron", title: "Preconstruction Manager", email: "sbergeron@example.com" },
    ],
  },
  {
    id: "org-jacobsen",
    name: "Jacobsen Construction",
    type: "gc",
    city: "Salt Lake City",
    state: "UT",
    relationship: "developing",
    paymentSpeed: "40 days",
    notes: "Two bids in, no award yet. Worth continued investment.",
    contacts: [{ name: "Priyanka Shah", title: "Estimator", email: "pshah@example.com" }],
  },
  {
    id: "org-ro",
    name: "R&O Construction",
    type: "gc",
    city: "Ogden",
    state: "UT",
    relationship: "strong",
    paymentSpeed: "30 days",
    notes: "Fast payers. Retail and distribution work up north.",
    contacts: [{ name: "Dallin Reeve", title: "Senior PM", email: "dreeve@example.com", phone: "801-555-0177" }],
  },
  {
    id: "org-wadman",
    name: "Wadman Corporation",
    type: "gc",
    city: "Ogden",
    state: "UT",
    relationship: "developing",
    notes: "Multifamily and hospitality. Price-driven.",
    contacts: [{ name: "Trevor Nakamura", title: "Estimator", email: "tnakamura@example.com" }],
  },
  {
    id: "org-zwick",
    name: "Zwick Construction",
    type: "gc",
    city: "Sandy",
    state: "UT",
    relationship: "new",
    notes: "First invitation. Unknown leveling behaviour.",
    contacts: [{ name: "Alison Fry", title: "Estimator", email: "afry@example.com" }],
  },
  {
    id: "org-hogan",
    name: "Hogan & Associates",
    type: "gc",
    city: "Centerville",
    state: "UT",
    relationship: "strong",
    paymentSpeed: "35 days",
    notes: "Public work specialist. Bonding almost always required.",
    contacts: [{ name: "Marisol Quintero", title: "Preconstruction", email: "mquintero@example.com" }],
  },
  {
    id: "org-gramoll",
    name: "Gramoll Construction",
    type: "gc",
    city: "Ogden",
    state: "UT",
    relationship: "developing",
    contacts: [{ name: "Ben Kirtley", title: "Estimator", email: "bkirtley@example.com" }],
  },
  {
    id: "org-budbailey",
    name: "Bud Bailey Construction",
    type: "gc",
    city: "Salt Lake City",
    state: "UT",
    relationship: "developing",
    notes: "Affordable housing pipeline. Tight budgets, steady volume.",
    contacts: [{ name: "Nia Fortenberry", title: "PM", email: "nfortenberry@example.com" }],
  },
  {
    id: "org-cameron",
    name: "Cameron Construction",
    type: "gc",
    city: "Orem",
    state: "UT",
    relationship: "new",
    contacts: [{ name: "Grant Whipple", title: "Estimator", email: "gwhipple@example.com" }],
  },
  {
    id: "org-ascent",
    name: "Ascent Construction",
    type: "gc",
    city: "Bountiful",
    state: "UT",
    relationship: "developing",
    contacts: [{ name: "Hana Lindquist", title: "Estimator", email: "hlindquist@example.com" }],
  },
];

export function buildSeed(now = new Date()): Database {
  const base = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  /** Date offset in days from today, as YYYY-MM-DD. */
  const d = (offset: number): string => {
    const x = new Date(base);
    x.setDate(x.getDate() + offset);
    return toISODate(x);
  };
  /** Same, with a time-of-day — used for bid deadlines. */
  const dt = (offset: number, time: string): string => `${d(offset)}T${time}`;
  const stamp = (offset: number, time = "09:30"): string =>
    new Date(`${d(offset)}T${time}:00`).toISOString();

  const projects: Project[] = [];
  const recipients: BidRecipient[] = [];
  const activities: Activity[] = [];
  let recSeq = 0;
  let actSeq = 0;

  const project = (p: Partial<Project> & Pick<Project, "id" | "code" | "name" | "city" | "stage" | "expectedValue">): Project => {
    const full: Project = {
      description: "",
      state: "UT",
      projectType: "commercial",
      workType: "new_construction",
      isPublic: false,
      probabilityOverride: null,
      materials: [],
      scopeFlags: [],
      dateConfidence: "probable",
      estimator: "Taylor Moss",
      competitors: [],
      createdAt: stamp(-60),
      updatedAt: stamp(-1),
      ...p,
    } as Project;
    projects.push(full);
    return full;
  };

  const recipient = (
    projectId: string,
    organizationId: string,
    r: Partial<BidRecipient> = {},
  ): BidRecipient => {
    recSeq += 1;
    const full: BidRecipient = {
      id: `rec-${String(recSeq).padStart(3, "0")}`,
      projectId,
      organizationId,
      revisions: [],
      ...r,
    };
    recipients.push(full);
    return full;
  };

  const activity = (
    projectId: string,
    a: Omit<Activity, "id" | "projectId">,
  ): void => {
    actSeq += 1;
    activities.push({ id: `act-${String(actSeq).padStart(3, "0")}`, projectId, ...a });
  };

  // -------------------------------------------------------------------------
  // 1 — The four-GC example: $350K unique, $1.4M of proposal activity.
  // -------------------------------------------------------------------------
  project({
    id: "prj-copperfield",
    code: "ER-2026-118",
    name: "Copperfield Medical Pavilion",
    description:
      "Full tear-off and replacement over occupied medical office. EPDM field with paver-set amenity terrace on the third-floor setback. Night and weekend phasing over the ambulatory wing.",
    addressLine: "5171 Cottonwood Street",
    city: "Murray",
    zip: "84107",
    projectType: "institutional",
    workType: "reroof",
    owner: "Copperfield Health Partners",
    architect: "Method Studio",
    source: "BuildingConnected invitation",
    trelloUrl: "https://trello.com/c/eliteroof-copperfield",
    bidPlatformUrl: "https://app.buildingconnected.com/projects/copperfield",
    stage: "shortlisted",
    expectedValue: 350_000,
    estimatedCost: 267_000,
    retainagePct: 5,
    cashFlowRisk: "medium",
    materials: ["epdm", "pavers", "insulation", "sheet_metal"],
    manufacturer: "Carlisle",
    warranty: "20-year NDL",
    roofAreaSqFt: 41_500,
    buildings: 1,
    stories: 3,
    scopeFlags: ["demolition", "pavers", "taper", "phased", "fall_protection"],
    invitationDate: d(-38),
    siteWalkDate: d(-31),
    rfiDeadline: d(-24),
    bidDueDate: dt(-19, "14:00"),
    bidSubmittedDate: d(-20),
    originalAwardDate: d(-5),
    anticipatedAwardDate: d(12),
    expectedContractDate: d(26),
    installStart: d(74),
    installEnd: d(131),
    dateConfidence: "probable",
    lastActivityDate: d(-2),
    projectManager: "Megan Alvarado",
    competition: "high",
    competitors: ["Summit Roofing Systems", "Beehive Commercial Roofing"],
    pricingPosition: "competitive",
    relationship: "preferred",
    priority: "high",
    fitScore: 8,
    scopeCompared: true,
    bidLeveled: true,
    pricingCurrent: true,
    winReason:
      "Only bidder who priced the paver terrace as a single responsibility. Okland has asked us to hold pricing.",
    primaryRisk:
      "Owner is still weighing deferring the terrace scope, which would cut roughly $78K out of the job.",
    valueEngineering:
      "Offered a ballasted alternate for the north field — $22K credit if the owner accepts a 15-year warranty.",
    createdAt: stamp(-38),
    updatedAt: stamp(-2),
  });
  recipient("prj-copperfield", "org-okland", {
    contactName: "Ryan Delacroix",
    contactEmail: "rdelacroix@example.com",
    contactPhone: "801-555-0142",
    submittedAmount: 350_000,
    submittedDate: d(-20),
    status: "Leveled — clarifications answered",
    lastContactDate: d(-2),
    nextFollowUpDate: d(0),
    nextFollowUpType: "award_timing",
    signal: "strong_positive",
    feedback:
      "Told us we are the number the owner is working from. Waiting on the owner's terrace decision.",
    clarifications:
      "Excludes structural deck repair beyond 200 SF; includes all tapered crickets per detail 7/A5.2.",
    revisions: [
      { id: "rev-1", revision: 0, amount: 362_400, date: d(-20), note: "Original proposal" },
      { id: "rev-2", revision: 1, amount: 350_000, date: d(-9), note: "Addendum 3 — reduced terrace paver area" },
    ],
  });
  recipient("prj-copperfield", "org-layton", {
    contactName: "Sasha Bergeron",
    contactEmail: "sbergeron@example.com",
    submittedAmount: 350_000,
    submittedDate: d(-20),
    status: "No feedback since submission",
    lastContactDate: d(-11),
    nextFollowUpDate: d(2),
    nextFollowUpType: "bid_leveling",
    signal: "neutral",
    revisions: [{ id: "rev-3", revision: 0, amount: 350_000, date: d(-20) }],
  });
  recipient("prj-copperfield", "org-jacobsen", {
    contactName: "Priyanka Shah",
    contactEmail: "pshah@example.com",
    submittedAmount: 350_000,
    submittedDate: d(-20),
    status: "Confirmed received",
    lastContactDate: d(-14),
    nextFollowUpDate: d(4),
    nextFollowUpType: "bid_leveling",
    signal: "neutral",
    revisions: [{ id: "rev-4", revision: 0, amount: 350_000, date: d(-20) }],
  });
  recipient("prj-copperfield", "org-zwick", {
    contactName: "Alison Fry",
    contactEmail: "afry@example.com",
    submittedAmount: 350_000,
    submittedDate: d(-19),
    status: "Late invitation — submitted day after bid date",
    lastContactDate: d(-19),
    nextFollowUpDate: d(6),
    nextFollowUpType: "confirm_receipt",
    signal: "neutral",
    revisions: [{ id: "rev-5", revision: 0, amount: 350_000, date: d(-19) }],
  });
  activity("prj-copperfield", {
    at: stamp(-2, "10:15"),
    kind: "touch",
    method: "call",
    contact: "Ryan Delacroix",
    recipientId: "rec-001",
    signal: "strong_positive",
    note: "Ryan says our number is the one the owner is working from. Terrace scope still undecided — owner meets Thursday.",
    summary: "Called Ryan Delacroix at Okland Construction",
    author: "Taylor Moss",
  });
  activity("prj-copperfield", {
    at: stamp(-9, "16:40"),
    kind: "bid_submitted",
    recipientId: "rec-001",
    summary: "Revision 1 submitted to Okland — $350,000 after Addendum 3",
    note: "Terrace paver area reduced by 1,900 SF per Addendum 3.",
    author: "Taylor Moss",
  });
  activity("prj-copperfield", {
    at: stamp(-14, "11:05"),
    kind: "touch",
    method: "email",
    contact: "Priyanka Shah",
    recipientId: "rec-003",
    signal: "neutral",
    note: "Confirmed receipt, no leveling scheduled yet.",
    summary: "Emailed Priyanka Shah at Jacobsen Construction",
    author: "Taylor Moss",
  });
  activity("prj-copperfield", {
    at: stamp(-20, "13:50"),
    kind: "bid_submitted",
    summary: "Original proposal issued to 4 general contractors — $362,400",
    author: "Taylor Moss",
  });
  activity("prj-copperfield", {
    at: stamp(-31, "08:00"),
    kind: "note",
    summary: "Attended pre-bid walk",
    note: "Deck is 1.5\" B-deck, sound. Two abandoned curbs to remove. Crane access off the east lot only before 7am.",
    author: "Taylor Moss",
  });

  // -------------------------------------------------------------------------
  // 2 — Large TPO in active estimating, bid closing this week.
  // -------------------------------------------------------------------------
  project({
    id: "prj-riverbend",
    code: "ER-2026-131",
    name: "Riverbend Logistics Center — Phase II",
    description:
      "New 412,000 SF distribution building. Mechanically attached TPO over tapered polyiso, full perimeter sheet metal, 74 curbs.",
    addressLine: "2900 North Ranch Road",
    city: "Lehi",
    zip: "84043",
    projectType: "commercial",
    workType: "new_construction",
    owner: "Riverbend Industrial Partners",
    architect: "Curtis Miner Architecture",
    source: "Invited by Big-D precon",
    trelloUrl: "https://trello.com/c/eliteroof-riverbend2",
    stage: "estimating",
    expectedValue: 2_150_000,
    estimatedCost: 1_752_000,
    retainagePct: 5,
    cashFlowRisk: "high",
    materials: ["tpo", "insulation", "sheet_metal"],
    manufacturer: "Carlisle",
    warranty: "20-year NDL",
    roofAreaSqFt: 412_000,
    buildings: 1,
    stories: 1,
    scopeFlags: ["crane", "taper", "fall_protection", "bonding"],
    invitationDate: d(-16),
    siteWalkDate: d(-9),
    rfiDeadline: d(3),
    bidDueDate: dt(6, "14:00"),
    anticipatedAwardDate: d(48),
    expectedContractDate: d(66),
    installStart: d(142),
    installEnd: d(268),
    dateConfidence: "rough",
    lastActivityDate: d(-1),
    competition: "high",
    competitors: ["Summit Roofing Systems", "Intermountain Roofing Co."],
    pricingPosition: "unknown",
    relationship: "strong",
    priority: "must_win",
    fitScore: 9,
    scopeCompared: false,
    bidLeveled: false,
    pricingCurrent: true,
    winReason:
      "Elite is one of two roofers in the valley with crews to cover 412,000 SF inside the schedule.",
    primaryRisk:
      "Peak working capital near $410K before the first draw. Bonding capacity needs confirming before we submit.",
    createdAt: stamp(-16),
    updatedAt: stamp(-1),
  });
  recipient("prj-riverbend", "org-bigd", {
    contactName: "Cole Bannister",
    contactEmail: "cbannister@example.com",
    contactPhone: "801-555-0119",
    status: "Estimating — not yet submitted",
    lastContactDate: d(-1),
    nextFollowUpDate: d(1),
    nextFollowUpType: "scope_clarification",
    signal: "positive",
    clarifications: "RFI 4 open: tapered package responsibility at the truck court canopies.",
  });
  recipient("prj-riverbend", "org-okland", {
    contactName: "Ryan Delacroix",
    contactEmail: "rdelacroix@example.com",
    status: "Estimating — not yet submitted",
    lastContactDate: d(-7),
    nextFollowUpDate: d(3),
    nextFollowUpType: "confirm_scope",
    signal: "neutral",
  });
  recipient("prj-riverbend", "org-ro", {
    contactName: "Dallin Reeve",
    contactEmail: "dreeve@example.com",
    status: "Estimating — not yet submitted",
    lastContactDate: d(-5),
    nextFollowUpDate: d(2),
    nextFollowUpType: "confirm_scope",
    signal: "neutral",
  });
  activity("prj-riverbend", {
    at: stamp(-1, "15:20"),
    kind: "touch",
    method: "email",
    contact: "Cole Bannister",
    recipientId: "rec-006",
    signal: "positive",
    note: "RFI 4 submitted on the canopy taper. Cole expects an addendum before bid day.",
    summary: "Emailed Cole Bannister at Big-D Construction",
    author: "Taylor Moss",
  });
  activity("prj-riverbend", {
    at: stamp(-9, "07:30"),
    kind: "note",
    summary: "Pre-bid meeting — 22 subs in attendance",
    note: "Owner confirmed a 2-phase turnover. Roof must be dried in on the east half by the end of the install window.",
    author: "Taylor Moss",
  });

  // -------------------------------------------------------------------------
  // 3 — $800K, pricing recently reconfirmed.
  // -------------------------------------------------------------------------
  project({
    id: "prj-stationpark",
    code: "ER-2026-096",
    name: "Station Park Retail — Block C",
    description:
      "Four retail shells plus a shared service corridor. PVC over polyiso, standing-seam metal accents at the entries.",
    addressLine: "140 North Union Avenue",
    city: "Farmington",
    zip: "84025",
    projectType: "commercial",
    workType: "new_construction",
    owner: "CenterCal Properties",
    architect: "AJC Architects",
    source: "Repeat client — R&O",
    trelloUrl: "https://trello.com/c/eliteroof-stationpark-c",
    stage: "shortlisted",
    expectedValue: 800_000,
    estimatedCost: 604_000,
    retainagePct: 5,
    cashFlowRisk: "medium",
    materials: ["pvc", "standing_seam", "insulation", "sheet_metal"],
    manufacturer: "Sika Sarnafil",
    warranty: "20-year NDL",
    roofAreaSqFt: 96_000,
    buildings: 4,
    stories: 1,
    scopeFlags: ["taper", "fall_protection"],
    invitationDate: d(-52),
    siteWalkDate: d(-45),
    bidDueDate: dt(-33, "16:00"),
    bidSubmittedDate: d(-34),
    originalAwardDate: d(-12),
    anticipatedAwardDate: d(9),
    expectedContractDate: d(24),
    installStart: d(96),
    installEnd: d(172),
    dateConfidence: "probable",
    lastActivityDate: d(-3),
    projectManager: "Dallin Reeve",
    competition: "medium",
    competitors: ["Beehive Commercial Roofing"],
    pricingPosition: "competitive",
    relationship: "strong",
    priority: "high",
    fitScore: 8,
    scopeCompared: true,
    bidLeveled: true,
    pricingCurrent: true,
    winReason:
      "R&O has awarded us the last two Station Park phases and knows our sequencing on multi-shell sites.",
    primaryRisk: "Membrane lead time pushed to 11 weeks — install start slips if award drags past next month.",
    createdAt: stamp(-52),
    updatedAt: stamp(-3),
  });
  recipient("prj-stationpark", "org-ro", {
    contactName: "Dallin Reeve",
    contactEmail: "dreeve@example.com",
    contactPhone: "801-555-0177",
    submittedAmount: 800_000,
    submittedDate: d(-34),
    status: "Pricing reconfirmed — held for 45 days",
    lastContactDate: d(-3),
    nextFollowUpDate: d(1),
    nextFollowUpType: "award_timing",
    signal: "positive",
    feedback: "Dallin reconfirmed our number is current and asked us to hold through the owner's GMP review.",
    revisions: [
      { id: "rev-6", revision: 0, amount: 812_500, date: d(-34) },
      { id: "rev-7", revision: 1, amount: 800_000, date: d(-3), note: "Reconfirmed pricing, escalation removed" },
    ],
  });
  activity("prj-stationpark", {
    at: stamp(-3, "14:05"),
    kind: "touch",
    method: "call",
    contact: "Dallin Reeve",
    recipientId: "rec-009",
    signal: "positive",
    note: "Pricing reconfirmed at $800,000 and held 45 days. GMP review with the owner is next week.",
    summary: "Called Dallin Reeve at R&O Construction",
    author: "Taylor Moss",
  });
  activity("prj-stationpark", {
    at: stamp(-34, "15:00"),
    kind: "bid_submitted",
    recipientId: "rec-009",
    summary: "Proposal submitted to R&O Construction — $812,500",
    author: "Taylor Moss",
  });

  // -------------------------------------------------------------------------
  // 4 — Multifamily with a wide potential range.
  // -------------------------------------------------------------------------
  project({
    id: "prj-wasatchridge",
    code: "ER-2026-127",
    name: "Wasatch Ridge Apartments — Buildings A–F",
    description:
      "Six three-story walk-up buildings plus a clubhouse. Owner is still deciding whether Elite carries all six buildings or only the flat-roof clubhouse and breezeways, so the range is genuinely wide.",
    addressLine: "1780 South Mill Road",
    city: "Vineyard",
    zip: "84059",
    projectType: "multifamily",
    workType: "new_construction",
    owner: "Ridgeline Residential",
    architect: "KTGY",
    source: "Wadman invitation",
    trelloUrl: "https://trello.com/c/eliteroof-wasatchridge",
    stage: "estimating",
    expectedValue: 780_000,
    valueRangeLow: 50_000,
    valueRangeHigh: 1_500_000,
    estimatedCost: 631_000,
    cashFlowRisk: "medium",
    materials: ["shingles", "tpo", "sheet_metal"],
    manufacturer: "GAF",
    warranty: "10-year system",
    roofAreaSqFt: 168_000,
    buildings: 7,
    stories: 3,
    scopeFlags: ["fall_protection", "phased"],
    invitationDate: d(-21),
    siteWalkDate: d(-13),
    bidDueDate: dt(11, "17:00"),
    anticipatedAwardDate: d(40),
    installStart: d(120),
    installEnd: d(300),
    dateConfidence: "rough",
    lastActivityDate: d(-4),
    competition: "high",
    pricingPosition: "unknown",
    relationship: "developing",
    priority: "normal",
    fitScore: 6,
    winReason: "Elite can self-perform both the shingle and the low-slope scope — most bidders can only do one.",
    primaryRisk:
      "Scope split is unresolved. At the low end this is a $50K clubhouse job; at the high end it is all six buildings.",
    createdAt: stamp(-21),
    updatedAt: stamp(-4),
  });
  recipient("prj-wasatchridge", "org-wadman", {
    contactName: "Trevor Nakamura",
    contactEmail: "tnakamura@example.com",
    status: "Estimating — awaiting scope split",
    lastContactDate: d(-4),
    nextFollowUpDate: d(2),
    nextFollowUpType: "scope_clarification",
    signal: "neutral",
    clarifications: "Asked whether shingle scope is carried by Elite or by the framer's roofing sub.",
  });
  recipient("prj-wasatchridge", "org-budbailey", {
    contactName: "Nia Fortenberry",
    contactEmail: "nfortenberry@example.com",
    status: "Estimating",
    lastContactDate: d(-8),
    nextFollowUpDate: d(5),
    nextFollowUpType: "confirm_scope",
    signal: "neutral",
  });
  activity("prj-wasatchridge", {
    at: stamp(-4, "09:10"),
    kind: "touch",
    method: "email",
    contact: "Trevor Nakamura",
    recipientId: "rec-010",
    signal: "neutral",
    note: "Asked again for the scope split between shingle and low-slope. Trevor is chasing the owner.",
    summary: "Emailed Trevor Nakamura at Wadman Corporation",
    author: "Dana Whitaker",
  });

  // -------------------------------------------------------------------------
  // 5 — Verbal award waiting on subcontract.
  // -------------------------------------------------------------------------
  project({
    id: "prj-cottonwood",
    code: "ER-2026-081",
    name: "Cottonwood Corporate Center III",
    description:
      "Reroof of a six-story office over an occupied building. PVC with a mechanical well platform rebuild and new lightning protection coordination.",
    addressLine: "2755 East Cottonwood Parkway",
    city: "Holladay",
    zip: "84121",
    projectType: "commercial",
    workType: "reroof",
    owner: "Cottonwood Realty Trust",
    architect: "GSBS Architects",
    source: "Referred by building engineer",
    trelloUrl: "https://trello.com/c/eliteroof-cottonwood3",
    stage: "verbal_award",
    expectedValue: 1_060_000,
    estimatedCost: 812_000,
    retainagePct: 10,
    cashFlowRisk: "medium",
    materials: ["pvc", "insulation", "sheet_metal", "coatings"],
    manufacturer: "Sika Sarnafil",
    warranty: "25-year NDL",
    roofAreaSqFt: 88_000,
    buildings: 1,
    stories: 6,
    scopeFlags: ["crane", "demolition", "taper", "phased", "fall_protection"],
    invitationDate: d(-88),
    bidDueDate: dt(-64, "15:00"),
    bidSubmittedDate: d(-65),
    originalAwardDate: d(-30),
    anticipatedAwardDate: d(-9),
    expectedContractDate: d(8),
    installStart: d(58),
    installEnd: d(122),
    dateConfidence: "probable",
    lastActivityDate: d(-6),
    projectManager: "Megan Alvarado",
    competition: "medium",
    pricingPosition: "competitive",
    relationship: "preferred",
    priority: "must_win",
    fitScore: 9,
    scopeCompared: true,
    bidLeveled: true,
    pricingCurrent: true,
    winReason: "Verbally selected. Elite's phasing plan kept the tenants' HVAC online through the well rebuild.",
    primaryRisk: "Subcontract has been 'a week away' for three weeks. Crew slot is being held.",
    createdAt: stamp(-88),
    updatedAt: stamp(-6),
  });
  recipient("prj-cottonwood", "org-okland", {
    contactName: "Megan Alvarado",
    contactEmail: "malvarado@example.com",
    submittedAmount: 1_060_000,
    submittedDate: d(-65),
    status: "Verbally awarded — subcontract in legal review",
    lastContactDate: d(-6),
    nextFollowUpDate: d(-2),
    nextFollowUpType: "contract_status",
    signal: "strong_positive",
    feedback: "Megan confirmed the award verbally. Waiting on the owner's counsel to release the subcontract form.",
    revisions: [{ id: "rev-8", revision: 0, amount: 1_060_000, date: d(-65) }],
  });
  activity("prj-cottonwood", {
    at: stamp(-6, "11:30"),
    kind: "touch",
    method: "call",
    contact: "Megan Alvarado",
    recipientId: "rec-012",
    signal: "positive",
    note: "Still in legal. Megan will push for release this week. Asked us to hold the September crew slot.",
    summary: "Called Megan Alvarado at Okland Construction",
    author: "Taylor Moss",
  });
  activity("prj-cottonwood", {
    at: stamp(-9, "10:00"),
    kind: "stage_change",
    summary: "Stage changed from Apparent Low / Preferred to Verbal Award / Intent",
    note: "Megan called with the verbal award.",
    author: "Taylor Moss",
  });

  // -------------------------------------------------------------------------
  // 6 — Signed, install several months out.
  // -------------------------------------------------------------------------
  project({
    id: "prj-silverfork",
    code: "ER-2025-402",
    name: "Silver Fork Distribution Center",
    description:
      "New 260,000 SF cold-shell distribution building. Adhered TPO, tapered crickets throughout, 1,900 LF of coping.",
    addressLine: "3550 West Midland Drive",
    city: "Ogden",
    zip: "84401",
    projectType: "commercial",
    workType: "new_construction",
    owner: "Silver Fork Industrial LLC",
    architect: "Method Studio",
    source: "R&O invitation",
    trelloUrl: "https://trello.com/c/eliteroof-silverfork",
    stage: "contracted",
    expectedValue: 2_420_000,
    estimatedCost: 1_935_000,
    retainagePct: 5,
    cashFlowRisk: "medium",
    materials: ["tpo", "insulation", "sheet_metal"],
    manufacturer: "Carlisle",
    warranty: "20-year NDL",
    roofAreaSqFt: 260_000,
    buildings: 1,
    stories: 1,
    scopeFlags: ["crane", "taper", "bonding", "fall_protection"],
    invitationDate: d(-160),
    bidDueDate: dt(-138, "14:00"),
    bidSubmittedDate: d(-139),
    anticipatedAwardDate: d(-96),
    expectedContractDate: d(-72),
    installStart: d(112),
    installEnd: d(206),
    dateConfidence: "firm",
    lastActivityDate: d(-11),
    projectManager: "Dallin Reeve",
    competition: "medium",
    pricingPosition: "competitive",
    relationship: "strong",
    priority: "high",
    fitScore: 9,
    scopeCompared: true,
    bidLeveled: true,
    pricingCurrent: true,
    contract: {
      executedValue: 2_420_000,
      changeOrders: 64_500,
      revenueEarned: 0,
      retainagePct: 5,
      contractDate: d(-72),
      bondIncluded: true,
      bondCost: 27_800,
    },
    winReason: "Won on schedule confidence and a self-performed sheet metal package.",
    primaryRisk: "Winter start. Deck must be dried in before the first hard freeze or the schedule pushes a month.",
    createdAt: stamp(-160),
    updatedAt: stamp(-11),
  });
  recipient("prj-silverfork", "org-ro", {
    contactName: "Dallin Reeve",
    contactEmail: "dreeve@example.com",
    submittedAmount: 2_420_000,
    submittedDate: d(-139),
    status: "Contracted",
    lastContactDate: d(-11),
    nextFollowUpDate: d(14),
    nextFollowUpType: "submittals",
    signal: "positive",
    feedback: "Submittal package due 60 days before mobilization.",
    revisions: [{ id: "rev-9", revision: 0, amount: 2_420_000, date: d(-139) }],
  });
  activity("prj-silverfork", {
    at: stamp(-11, "13:15"),
    kind: "touch",
    method: "email",
    contact: "Dallin Reeve",
    recipientId: "rec-013",
    signal: "positive",
    note: "CO-01 executed for added roof hatch and two curbs — $64,500.",
    summary: "Change order 01 executed — $64,500",
    author: "Taylor Moss",
  });
  activity("prj-silverfork", {
    at: stamp(-72, "16:00"),
    kind: "stage_change",
    summary: "Stage changed from Contract / LOI Received to Contracted",
    note: "Subcontract executed at $2,420,000.",
    author: "Taylor Moss",
  });

  // -------------------------------------------------------------------------
  // 7 — Lost, with a known competitor and reason.
  // -------------------------------------------------------------------------
  project({
    id: "prj-provocanyon",
    code: "ER-2026-064",
    name: "Provo Canyon Athletic Complex",
    description:
      "Field house and natatorium reroof. Standing-seam metal over the arena, modified bitumen at the mechanical mezzanine.",
    addressLine: "1450 North University Avenue",
    city: "Provo",
    zip: "84604",
    projectType: "institutional",
    workType: "reroof",
    isPublic: true,
    owner: "Provo City School District",
    architect: "VCBO Architecture",
    source: "Public bid advertisement",
    trelloUrl: "https://trello.com/c/eliteroof-provocanyon",
    stage: "lost",
    expectedValue: 1_180_000,
    estimatedCost: 972_000,
    materials: ["standing_seam", "mod_bit", "sheet_metal"],
    manufacturer: "Holcim / Firestone",
    roofAreaSqFt: 74_000,
    buildings: 2,
    scopeFlags: ["prevailing_wage", "bonding", "crane", "fall_protection"],
    invitationDate: d(-124),
    bidDueDate: dt(-97, "14:00"),
    bidSubmittedDate: d(-97),
    anticipatedAwardDate: d(-70),
    dateConfidence: "unknown",
    lastActivityDate: d(-68),
    competition: "high",
    competitors: ["Intermountain Roofing Co.", "Summit Roofing Systems"],
    pricingPosition: "high",
    relationship: "developing",
    priority: "normal",
    fitScore: 5,
    outcome: {
      result: "lost",
      date: d(-68),
      awardedTo: "Intermountain Roofing Co.",
      winningAmount: 1_054_000,
      reason:
        "Priced $126,000 above the winner. Our metal panel supplier quoted a 14-week lead time and we carried premium freight to protect the schedule.",
      competitor: "Intermountain Roofing Co.",
      lessons:
        "Get a second panel quote on any job with more than 20,000 SF of standing seam. Freight assumption cost us the job, not labour.",
      eligibleForRebid: false,
    },
    createdAt: stamp(-124),
    updatedAt: stamp(-68),
  });
  recipient("prj-provocanyon", "org-hogan", {
    contactName: "Marisol Quintero",
    contactEmail: "mquintero@example.com",
    submittedAmount: 1_180_000,
    submittedDate: d(-97),
    status: "Not selected",
    lastContactDate: d(-68),
    signal: "strong_negative",
    feedback: "Public bid tab: Intermountain $1,054,000; Elite $1,180,000; Summit $1,197,500.",
    revisions: [{ id: "rev-10", revision: 0, amount: 1_180_000, date: d(-97) }],
  });
  activity("prj-provocanyon", {
    at: stamp(-68, "09:00"),
    kind: "stage_change",
    summary: "Stage changed from Bid Submitted to Lost",
    note: "Bid tab published. Intermountain low at $1,054,000.",
    author: "Taylor Moss",
  });

  // -------------------------------------------------------------------------
  // 8 — Public school reroof, active follow-up.
  // -------------------------------------------------------------------------
  project({
    id: "prj-granitepeaks",
    code: "ER-2026-108",
    name: "Granite Peaks High School — Roof Replacement",
    description:
      "Summer-window replacement over classroom wings B, C and D. PVC with full tapered package and 62 new drains.",
    addressLine: "9800 South 1300 East",
    city: "Sandy",
    zip: "84094",
    projectType: "municipal",
    workType: "reroof",
    isPublic: true,
    owner: "Canyons School District",
    architect: "MHTN Architects",
    source: "Public bid advertisement",
    trelloUrl: "https://trello.com/c/eliteroof-granitepeaks",
    stage: "active_followup",
    expectedValue: 1_420_000,
    estimatedCost: 1_136_000,
    retainagePct: 5,
    cashFlowRisk: "low",
    materials: ["pvc", "insulation", "sheet_metal"],
    manufacturer: "Johns Manville",
    warranty: "20-year NDL",
    roofAreaSqFt: 152_000,
    buildings: 3,
    stories: 2,
    scopeFlags: ["prevailing_wage", "bonding", "demolition", "taper", "drains", "fall_protection"],
    invitationDate: d(-46),
    bidDueDate: dt(-27, "14:00"),
    bidSubmittedDate: d(-27),
    anticipatedAwardDate: d(21),
    expectedContractDate: d(35),
    installStart: d(196),
    installEnd: d(252),
    dateConfidence: "firm",
    lastActivityDate: d(-5),
    competition: "medium",
    competitors: ["Summit Roofing Systems"],
    pricingPosition: "competitive",
    relationship: "strong",
    priority: "high",
    fitScore: 8,
    scopeCompared: true,
    bidLeveled: true,
    pricingCurrent: true,
    winReason: "Elite has finished the last three Canyons District summer windows on time.",
    primaryRisk: "Board approval is on the calendar but has slipped twice already.",
    createdAt: stamp(-46),
    updatedAt: stamp(-5),
  });
  recipient("prj-granitepeaks", "org-hogan", {
    contactName: "Marisol Quintero",
    contactEmail: "mquintero@example.com",
    submittedAmount: 1_420_000,
    submittedDate: d(-27),
    status: "Awaiting board approval",
    lastContactDate: d(-5),
    nextFollowUpDate: d(0),
    nextFollowUpType: "award_timing",
    signal: "positive",
    waitingOn: null,
    feedback: "Marisol expects the board to act at the next meeting.",
    revisions: [{ id: "rev-11", revision: 0, amount: 1_420_000, date: d(-27) }],
  });
  activity("prj-granitepeaks", {
    at: stamp(-5, "15:45"),
    kind: "touch",
    method: "call",
    contact: "Marisol Quintero",
    recipientId: "rec-015",
    signal: "positive",
    note: "Board item is agendized. Marisol says our number held up in leveling.",
    summary: "Called Marisol Quintero at Hogan & Associates",
    author: "Taylor Moss",
  });

  // -------------------------------------------------------------------------
  // 9 — Apparent low / preferred.
  // -------------------------------------------------------------------------
  project({
    id: "prj-altaview",
    code: "ER-2026-112",
    name: "Alta View Surgical Center",
    description:
      "New single-story ambulatory surgery center. Adhered TPO, heavy mechanical screening, acoustic curbs.",
    addressLine: "9500 South 1300 East",
    city: "Sandy",
    zip: "84094",
    projectType: "institutional",
    workType: "new_construction",
    owner: "Alta View Health",
    architect: "Method Studio",
    source: "Layton precon invitation",
    trelloUrl: "https://trello.com/c/eliteroof-altaview",
    stage: "apparent_low",
    expectedValue: 640_000,
    estimatedCost: 486_000,
    retainagePct: 5,
    cashFlowRisk: "low",
    materials: ["tpo", "insulation", "sheet_metal"],
    manufacturer: "Carlisle",
    warranty: "20-year NDL",
    roofAreaSqFt: 58_000,
    buildings: 1,
    stories: 1,
    scopeFlags: ["taper", "fall_protection"],
    invitationDate: d(-58),
    bidDueDate: dt(-40, "15:00"),
    bidSubmittedDate: d(-40),
    anticipatedAwardDate: d(14),
    expectedContractDate: d(29),
    installStart: d(88),
    installEnd: d(130),
    dateConfidence: "probable",
    lastActivityDate: d(-4),
    projectManager: "Sasha Bergeron",
    competition: "medium",
    pricingPosition: "low",
    relationship: "strong",
    priority: "high",
    fitScore: 8,
    scopeCompared: true,
    bidLeveled: true,
    pricingCurrent: true,
    winReason: "Apparent low after leveling. Layton has us carrying the acoustic curb scope no one else priced.",
    primaryRisk: "Owner financing close has moved once already.",
    createdAt: stamp(-58),
    updatedAt: stamp(-4),
  });
  recipient("prj-altaview", "org-layton", {
    contactName: "Sasha Bergeron",
    contactEmail: "sbergeron@example.com",
    submittedAmount: 640_000,
    submittedDate: d(-40),
    status: "Apparent low after leveling",
    lastContactDate: d(-4),
    nextFollowUpDate: d(3),
    nextFollowUpType: "award_timing",
    signal: "strong_positive",
    feedback: "Sasha confirmed we are the carried number in the GMP.",
    revisions: [{ id: "rev-12", revision: 0, amount: 658_000, date: d(-40) },
      { id: "rev-13", revision: 1, amount: 640_000, date: d(-18), note: "Leveled — removed duplicate walkway pad scope" }],
  });
  activity("prj-altaview", {
    at: stamp(-4, "10:40"),
    kind: "touch",
    method: "email",
    contact: "Sasha Bergeron",
    recipientId: "rec-016",
    signal: "strong_positive",
    note: "We are the carried number. Award follows the owner's financing close.",
    summary: "Emailed Sasha Bergeron at Layton Construction",
    author: "Taylor Moss",
  });

  // -------------------------------------------------------------------------
  // 10 — Contract / LOI received.
  // -------------------------------------------------------------------------
  project({
    id: "prj-emigration",
    code: "ER-2026-073",
    name: "Emigration Place Condominiums",
    description:
      "Reroof of three connected condo buildings with a shared podium deck. EPDM field, pavers over the amenity deck.",
    addressLine: "1275 East Emigration Canyon Road",
    city: "Salt Lake City",
    zip: "84108",
    projectType: "multifamily",
    workType: "reroof",
    owner: "Emigration Place HOA",
    source: "Direct to HOA via Ascent",
    trelloUrl: "https://trello.com/c/eliteroof-emigration",
    stage: "contract_received",
    expectedValue: 915_000,
    estimatedCost: 704_000,
    retainagePct: 10,
    cashFlowRisk: "high",
    materials: ["epdm", "pavers", "insulation", "sheet_metal"],
    manufacturer: "Carlisle",
    warranty: "20-year NDL",
    roofAreaSqFt: 71_000,
    buildings: 3,
    stories: 4,
    scopeFlags: ["demolition", "pavers", "taper", "phased", "fall_protection"],
    invitationDate: d(-102),
    bidDueDate: dt(-80, "17:00"),
    bidSubmittedDate: d(-81),
    anticipatedAwardDate: d(-21),
    expectedContractDate: d(5),
    installStart: d(46),
    installEnd: d(118),
    dateConfidence: "probable",
    lastActivityDate: d(-7),
    competition: "low",
    pricingPosition: "competitive",
    relationship: "developing",
    priority: "high",
    fitScore: 7,
    scopeCompared: true,
    bidLeveled: true,
    pricingCurrent: true,
    winReason: "Only bidder willing to phase around resident parking under the podium.",
    primaryRisk: "HOA reserve draw schedule — 10% retainage on a $915K job is real working capital.",
    createdAt: stamp(-102),
    updatedAt: stamp(-7),
  });
  recipient("prj-emigration", "org-ascent", {
    contactName: "Hana Lindquist",
    contactEmail: "hlindquist@example.com",
    submittedAmount: 915_000,
    submittedDate: d(-81),
    status: "Contract received — in review",
    lastContactDate: d(-7),
    nextFollowUpDate: d(1),
    nextFollowUpType: "contract_status",
    signal: "strong_positive",
    feedback: "Subcontract received. Two insurance exhibits need redlining before signature.",
    revisions: [{ id: "rev-14", revision: 0, amount: 915_000, date: d(-81) }],
  });
  activity("prj-emigration", {
    at: stamp(-7, "12:00"),
    kind: "note",
    summary: "Subcontract received for review",
    note: "Redlining the additional-insured and consequential-damages waiver exhibits.",
    author: "Taylor Moss",
  });

  // -------------------------------------------------------------------------
  // 11 — Overdue follow-up and going quiet.
  // -------------------------------------------------------------------------
  project({
    id: "prj-riverton",
    code: "ER-2026-088",
    name: "Riverton Distribution Annex",
    description: "Reroof over an active warehouse annex. Ballasted EPDM removal, new adhered TPO.",
    addressLine: "12600 South Pony Express Road",
    city: "Riverton",
    zip: "84065",
    projectType: "commercial",
    workType: "reroof",
    owner: "Pony Express Holdings",
    source: "Cold outreach — building owner",
    trelloUrl: "https://trello.com/c/eliteroof-riverton",
    stage: "active_followup",
    expectedValue: 455_000,
    estimatedCost: 369_000,
    materials: ["tpo", "ballast", "insulation"],
    manufacturer: "Versico",
    roofAreaSqFt: 62_000,
    buildings: 1,
    stories: 1,
    scopeFlags: ["demolition", "phased", "fall_protection"],
    invitationDate: d(-71),
    bidDueDate: dt(-54, "16:00"),
    bidSubmittedDate: d(-55),
    anticipatedAwardDate: d(-14),
    installStart: d(64),
    installEnd: d(104),
    dateConfidence: "rough",
    lastActivityDate: d(-23),
    competition: "unknown",
    pricingPosition: "unknown",
    relationship: "new",
    priority: "normal",
    fitScore: 6,
    primaryRisk: "Owner has gone quiet for three weeks. Award date already passed without word.",
    createdAt: stamp(-71),
    updatedAt: stamp(-23),
  });
  recipient("prj-riverton", "org-gramoll", {
    contactName: "Ben Kirtley",
    contactEmail: "bkirtley@example.com",
    submittedAmount: 455_000,
    submittedDate: d(-55),
    status: "No response in three weeks",
    lastContactDate: d(-23),
    nextFollowUpDate: d(-6),
    nextFollowUpType: "award_timing",
    signal: "negative",
    revisions: [{ id: "rev-15", revision: 0, amount: 455_000, date: d(-55) }],
  });
  activity("prj-riverton", {
    at: stamp(-23, "08:45"),
    kind: "touch",
    method: "email",
    contact: "Ben Kirtley",
    recipientId: "rec-018",
    signal: "negative",
    note: "Third email with no reply. Trying a call next.",
    summary: "Emailed Ben Kirtley at Gramoll Construction",
    author: "Taylor Moss",
  });

  // -------------------------------------------------------------------------
  // 12 — Bid submitted, quiet but healthy.
  // -------------------------------------------------------------------------
  project({
    id: "prj-uinta",
    code: "ER-2026-121",
    name: "Uinta Business Park — Building 4",
    description: "New flex-industrial shell. Mechanically attached TPO, minimal curb work.",
    addressLine: "480 West Uinta Way",
    city: "Heber City",
    zip: "84032",
    projectType: "commercial",
    workType: "new_construction",
    owner: "Uinta Park Partners",
    source: "Cameron Construction invitation",
    trelloUrl: "https://trello.com/c/eliteroof-uinta4",
    stage: "submitted",
    expectedValue: 385_000,
    estimatedCost: 316_000,
    materials: ["tpo", "insulation", "sheet_metal"],
    manufacturer: "GAF",
    roofAreaSqFt: 48_000,
    buildings: 1,
    stories: 1,
    scopeFlags: ["fall_protection", "winter"],
    invitationDate: d(-25),
    bidDueDate: dt(-8, "14:00"),
    bidSubmittedDate: d(-8),
    anticipatedAwardDate: d(25),
    installStart: d(150),
    installEnd: d(184),
    dateConfidence: "rough",
    lastActivityDate: d(-8),
    competition: "unknown",
    relationship: "new",
    priority: "normal",
    fitScore: 6,
    createdAt: stamp(-25),
    updatedAt: stamp(-8),
  });
  recipient("prj-uinta", "org-cameron", {
    contactName: "Grant Whipple",
    contactEmail: "gwhipple@example.com",
    submittedAmount: 385_000,
    submittedDate: d(-8),
    status: "Submitted — awaiting confirmation",
    lastContactDate: d(-8),
    nextFollowUpDate: d(1),
    nextFollowUpType: "confirm_receipt",
    signal: "neutral",
    revisions: [{ id: "rev-16", revision: 0, amount: 385_000, date: d(-8) }],
  });

  // -------------------------------------------------------------------------
  // 13 — Unscheduled follow-up (active, submitted, nothing booked).
  // -------------------------------------------------------------------------
  project({
    id: "prj-draperpw",
    code: "ER-2026-124",
    name: "Draper City Public Works Facility",
    description: "New fleet maintenance and salt storage buildings. Standing-seam metal over the salt barn.",
    addressLine: "12900 South Vestry Road",
    city: "Draper",
    zip: "84020",
    projectType: "municipal",
    workType: "new_construction",
    isPublic: true,
    owner: "Draper City",
    architect: "CRSA",
    source: "Public bid advertisement",
    trelloUrl: "https://trello.com/c/eliteroof-draperpw",
    stage: "submitted",
    expectedValue: 520_000,
    estimatedCost: 429_000,
    materials: ["standing_seam", "tpo", "sheet_metal"],
    manufacturer: "Holcim / Firestone",
    roofAreaSqFt: 54_000,
    buildings: 2,
    scopeFlags: ["prevailing_wage", "bonding", "crane", "fall_protection"],
    invitationDate: d(-30),
    bidDueDate: dt(-13, "14:00"),
    bidSubmittedDate: d(-13),
    anticipatedAwardDate: d(18),
    installStart: d(168),
    installEnd: d(214),
    dateConfidence: "rough",
    lastActivityDate: d(-13),
    competition: "high",
    relationship: "new",
    priority: "normal",
    fitScore: 5,
    createdAt: stamp(-30),
    updatedAt: stamp(-13),
  });
  recipient("prj-draperpw", "org-zwick", {
    contactName: "Alison Fry",
    contactEmail: "afry@example.com",
    submittedAmount: 520_000,
    submittedDate: d(-13),
    status: "Submitted",
    lastContactDate: d(-13),
    nextFollowUpDate: null,
    nextFollowUpType: null,
    signal: "neutral",
    revisions: [{ id: "rev-17", revision: 0, amount: 520_000, date: d(-13) }],
  });

  // -------------------------------------------------------------------------
  // 14 — Waiting on a known future event.
  // -------------------------------------------------------------------------
  project({
    id: "prj-sugarhouse",
    code: "ER-2026-129",
    name: "Sugar House Mixed-Use Podium",
    description:
      "Hot-rubber podium deck under a paver plaza and planters, with a separate TPO tower roof. Coordination-heavy.",
    addressLine: "2100 South Highland Drive",
    city: "Salt Lake City",
    zip: "84106",
    projectType: "multifamily",
    workType: "new_construction",
    owner: "Highland Yard Development",
    architect: "AJC Architects",
    source: "Big-D invitation",
    trelloUrl: "https://trello.com/c/eliteroof-sugarhouse",
    stage: "estimating",
    expectedValue: 1_250_000,
    estimatedCost: 1_012_000,
    materials: ["hydrotech", "pavers", "green_roof", "tpo", "insulation"],
    manufacturer: "Hydrotech",
    warranty: "20-year",
    roofAreaSqFt: 64_000,
    buildings: 2,
    stories: 7,
    scopeFlags: ["crane", "pavers", "drains", "taper", "fall_protection", "phased"],
    invitationDate: d(-12),
    siteWalkDate: d(-3),
    rfiDeadline: d(9),
    bidDueDate: dt(18, "15:00"),
    anticipatedAwardDate: d(58),
    installStart: d(190),
    installEnd: d(305),
    dateConfidence: "rough",
    lastActivityDate: d(-3),
    competition: "low",
    pricingPosition: "unknown",
    relationship: "strong",
    priority: "must_win",
    fitScore: 9,
    winReason: "Very few valley roofers self-perform hot rubber under an occupied plaza.",
    primaryRisk: "Waterproofing warranty boundary between our scope and the concrete podium.",
    createdAt: stamp(-12),
    updatedAt: stamp(-3),
  });
  recipient("prj-sugarhouse", "org-bigd", {
    contactName: "Cole Bannister",
    contactEmail: "cbannister@example.com",
    status: "Estimating — waiting on structural addendum",
    lastContactDate: d(-3),
    nextFollowUpDate: null,
    nextFollowUpType: null,
    waitingOn: `Structural addendum expected ${d(9)}`,
    signal: "positive",
  });
  activity("prj-sugarhouse", {
    at: stamp(-3, "07:45"),
    kind: "note",
    summary: "Site walk with Big-D and the waterproofing consultant",
    note: "Consultant wants a mock-up at the planter curb before we price the flashing detail.",
    author: "Taylor Moss",
  });

  // -------------------------------------------------------------------------
  // 15 — Identified, early.
  // -------------------------------------------------------------------------
  project({
    id: "prj-cachevalley",
    code: "ER-2026-133",
    name: "Cache Valley Cold Storage",
    description:
      "Rumoured 300,000 SF cold storage facility. Owner has selected an architect; no invitation yet.",
    city: "Logan",
    zip: "84341",
    projectType: "commercial",
    workType: "new_construction",
    owner: "Cache Valley Cold LLC",
    source: "Industry contact",
    stage: "identified",
    expectedValue: 1_800_000,
    materials: ["tpo", "insulation"],
    roofAreaSqFt: 300_000,
    buildings: 1,
    scopeFlags: ["crane", "taper"],
    installStart: d(320),
    installEnd: d(430),
    dateConfidence: "unknown",
    lastActivityDate: d(-9),
    competition: "unknown",
    relationship: "new",
    priority: "normal",
    fitScore: 7,
    estimator: "Dana Whitaker",
    createdAt: stamp(-9),
    updatedAt: stamp(-9),
  });
  recipient("prj-cachevalley", "org-jacobsen", {
    contactName: "Priyanka Shah",
    contactEmail: "pshah@example.com",
    status: "Tracking — no invitation yet",
    lastContactDate: d(-9),
    nextFollowUpDate: d(7),
    nextFollowUpType: "relationship",
    signal: "neutral",
  });

  // -------------------------------------------------------------------------
  // 16 — Invited, estimating not started.
  // -------------------------------------------------------------------------
  project({
    id: "prj-bearhollow",
    code: "ER-2026-134",
    name: "Bear Hollow Townhomes — Phase 3",
    description: "42 townhome units. Shingles with metal accent roofs over the entries.",
    addressLine: "4200 Bear Hollow Drive",
    city: "Park City",
    zip: "84098",
    projectType: "multifamily",
    workType: "new_construction",
    owner: "Bear Hollow Development",
    source: "Wadman invitation",
    trelloUrl: "https://trello.com/c/eliteroof-bearhollow3",
    stage: "invited",
    expectedValue: 690_000,
    materials: ["shingles", "standing_seam", "sheet_metal"],
    manufacturer: "Owens Corning",
    roofAreaSqFt: 96_000,
    buildings: 9,
    stories: 3,
    scopeFlags: ["winter", "fall_protection"],
    invitationDate: d(-5),
    bidDueDate: dt(22, "17:00"),
    installStart: d(220),
    installEnd: d(340),
    dateConfidence: "unknown",
    lastActivityDate: d(-5),
    competition: "high",
    relationship: "developing",
    priority: "low",
    fitScore: 4,
    estimator: "Marcus Idle",
    primaryRisk: "Park City winter window and steep-slope labour availability.",
    createdAt: stamp(-5),
    updatedAt: stamp(-5),
  });
  recipient("prj-bearhollow", "org-wadman", {
    contactName: "Trevor Nakamura",
    contactEmail: "tnakamura@example.com",
    status: "Invitation received",
    lastContactDate: d(-5),
    nextFollowUpDate: d(4),
    nextFollowUpType: "confirm_scope",
    signal: "neutral",
  });

  // -------------------------------------------------------------------------
  // 17 — Dormant / postponed.
  // -------------------------------------------------------------------------
  project({
    id: "prj-legacycrossing",
    code: "ER-2025-388",
    name: "Legacy Crossing Hotel",
    description: "Six-story select-service hotel. Owner paused the project pending refinancing.",
    addressLine: "950 West Legacy Parkway",
    city: "Centerville",
    zip: "84014",
    projectType: "commercial",
    workType: "new_construction",
    owner: "Legacy Hospitality Group",
    source: "Hogan invitation",
    trelloUrl: "https://trello.com/c/eliteroof-legacycrossing",
    stage: "dormant",
    expectedValue: 720_000,
    estimatedCost: 583_000,
    materials: ["tpo", "insulation", "sheet_metal"],
    roofAreaSqFt: 42_000,
    buildings: 1,
    stories: 6,
    scopeFlags: ["crane", "fall_protection"],
    invitationDate: d(-210),
    bidDueDate: dt(-188, "14:00"),
    bidSubmittedDate: d(-188),
    dateConfidence: "unknown",
    lastActivityDate: d(-96),
    competition: "medium",
    relationship: "strong",
    priority: "low",
    fitScore: 6,
    primaryRisk: "Refinancing. Owner said 'check back after rates move'.",
    createdAt: stamp(-210),
    updatedAt: stamp(-96),
  });
  recipient("prj-legacycrossing", "org-hogan", {
    contactName: "Marisol Quintero",
    contactEmail: "mquintero@example.com",
    submittedAmount: 720_000,
    submittedDate: d(-188),
    status: "Postponed by owner",
    lastContactDate: d(-96),
    nextFollowUpDate: d(30),
    nextFollowUpType: "relationship",
    signal: "neutral",
    revisions: [{ id: "rev-18", revision: 0, amount: 720_000, date: d(-188) }],
  });

  // -------------------------------------------------------------------------
  // 18 — No bid.
  // -------------------------------------------------------------------------
  project({
    id: "prj-timpanogos",
    code: "ER-2026-101",
    name: "Timpanogos Tech Campus — Roof Restoration",
    description: "Silicone restoration over 190,000 SF of aged TPO across five buildings.",
    addressLine: "1400 North Technology Way",
    city: "Orem",
    zip: "84057",
    projectType: "commercial",
    workType: "restoration",
    owner: "Timpanogos Campus Owner LLC",
    source: "Zwick invitation",
    stage: "no_bid",
    expectedValue: 640_000,
    materials: ["coatings"],
    roofAreaSqFt: 190_000,
    buildings: 5,
    scopeFlags: ["fall_protection"],
    invitationDate: d(-51),
    bidDueDate: dt(-37, "14:00"),
    dateConfidence: "unknown",
    lastActivityDate: d(-44),
    relationship: "new",
    priority: "low",
    fitScore: 2,
    outcome: {
      result: "no_bid",
      date: d(-44),
      reason:
        "Declined. Coating-only restoration at this scale ties up crews for six weeks at a margin we cannot justify against the Riverbend window.",
      eligibleForRebid: true,
    },
    createdAt: stamp(-51),
    updatedAt: stamp(-44),
  });
  recipient("prj-timpanogos", "org-zwick", {
    contactName: "Alison Fry",
    contactEmail: "afry@example.com",
    status: "Declined to bid",
    lastContactDate: d(-44),
    signal: "neutral",
  });

  // -------------------------------------------------------------------------
  // 19 — Cancelled.
  // -------------------------------------------------------------------------
  project({
    id: "prj-westvalley",
    code: "ER-2026-090",
    name: "West Valley Ice Center Addition",
    description: "Rink addition with an insulated metal panel roof. Bond referendum failed.",
    addressLine: "3200 South Decker Lake Drive",
    city: "West Valley City",
    zip: "84119",
    projectType: "municipal",
    workType: "new_construction",
    isPublic: true,
    owner: "West Valley City",
    source: "Public bid advertisement",
    stage: "cancelled",
    expectedValue: 480_000,
    materials: ["standing_seam", "sheet_metal"],
    roofAreaSqFt: 38_000,
    buildings: 1,
    scopeFlags: ["prevailing_wage", "bonding"],
    invitationDate: d(-140),
    bidDueDate: dt(-118, "14:00"),
    bidSubmittedDate: d(-118),
    dateConfidence: "unknown",
    lastActivityDate: d(-77),
    relationship: "developing",
    priority: "low",
    outcome: {
      result: "cancelled",
      date: d(-77),
      reason: "Bond referendum failed. City shelved the addition indefinitely.",
      eligibleForRebid: true,
    },
    createdAt: stamp(-140),
    updatedAt: stamp(-77),
  });
  recipient("prj-westvalley", "org-hogan", {
    contactName: "Marisol Quintero",
    submittedAmount: 480_000,
    submittedDate: d(-118),
    status: "Cancelled",
    lastContactDate: d(-77),
    revisions: [{ id: "rev-19", revision: 0, amount: 480_000, date: d(-118) }],
  });

  // -------------------------------------------------------------------------
  // 20 — Second contracted job, so the forecast shows a real collision.
  // -------------------------------------------------------------------------
  project({
    id: "prj-mountainview",
    code: "ER-2026-045",
    name: "Mountain View Corporate Campus — Building B",
    description: "Reroof of a two-building office campus. Adhered TPO over recover board.",
    addressLine: "6100 South Fashion Boulevard",
    city: "Murray",
    zip: "84107",
    projectType: "commercial",
    workType: "reroof",
    owner: "Mountain View Properties",
    source: "Repeat client",
    trelloUrl: "https://trello.com/c/eliteroof-mountainview-b",
    stage: "contracted",
    expectedValue: 1_180_000,
    estimatedCost: 917_000,
    retainagePct: 5,
    cashFlowRisk: "low",
    materials: ["tpo", "insulation", "sheet_metal"],
    manufacturer: "Carlisle",
    warranty: "20-year NDL",
    roofAreaSqFt: 104_000,
    buildings: 2,
    stories: 2,
    scopeFlags: ["demolition", "taper", "phased", "fall_protection"],
    invitationDate: d(-190),
    bidDueDate: dt(-168, "15:00"),
    bidSubmittedDate: d(-168),
    anticipatedAwardDate: d(-130),
    dateConfidence: "firm",
    installStart: d(96),
    installEnd: d(158),
    lastActivityDate: d(-16),
    projectManager: "Megan Alvarado",
    competition: "low",
    pricingPosition: "competitive",
    relationship: "preferred",
    priority: "high",
    fitScore: 9,
    scopeCompared: true,
    bidLeveled: true,
    pricingCurrent: true,
    contract: {
      executedValue: 1_180_000,
      changeOrders: 0,
      revenueEarned: 142_000,
      retainagePct: 5,
      contractDate: d(-118),
      bondIncluded: false,
      bondCost: null,
    },
    winReason: "Third campus building in four years. Owner does not re-bid our work.",
    createdAt: stamp(-190),
    updatedAt: stamp(-16),
  });
  recipient("prj-mountainview", "org-okland", {
    contactName: "Megan Alvarado",
    contactEmail: "malvarado@example.com",
    submittedAmount: 1_180_000,
    submittedDate: d(-168),
    status: "Contracted — submittals approved",
    lastContactDate: d(-16),
    nextFollowUpDate: d(9),
    nextFollowUpType: "schedule_confirmation",
    signal: "positive",
    revisions: [{ id: "rev-20", revision: 0, amount: 1_180_000, date: d(-168) }],
  });
  activity("prj-mountainview", {
    at: stamp(-16, "09:20"),
    kind: "note",
    summary: "Submittals approved — material released",
    note: "Carlisle order placed. Delivery scheduled two weeks before mobilization.",
    author: "Taylor Moss",
  });

  return {
    projects,
    recipients,
    organizations: ORGS,
    activities,
    updatedAt: new Date().toISOString(),
  };
}
